<?php

/**
 * @file
 * Domain-based access control for menu link.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Plugin\PluginBase;
use Drupal\domain_menu_access\Plugin\Block\DomainMenuAccessMenuBlock;
use Drupal\system\Entity\Menu;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Fires only if Devel Generate module is present, to assign test menu
 * link content to domains.
 */
function domain_menu_access_menu_link_content_presave(EntityInterface $node) {
  domain_access_presave_generate($node);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\menu_link_content\MenuLinkContentForm.
 *
 * Move Domain Access fields to an advanced tab like other node settings.
 */
function domain_menu_access_form_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\menu_link_content\Form\MenuLinkContentForm $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\menu_link_content\Entity\MenuLinkContent $entity */
  $entity = $form_object->getEntity();

  /** @var \Drupal\system\MenuInterface $menu */
  $menu = Menu::load($entity->getMenuName());
  if ($menu->getThirdPartySetting('domain_menu_access', 'access_enabled')) {
    $form['domain'] = array(
      '#type' => 'details',
      '#title' => t('Domain'),
      '#open' => TRUE,
      '#weight' => 25,
    );

    $form[DOMAIN_ACCESS_FIELD]['#group'] = 'domain';
    $form[DOMAIN_ACCESS_ALL_FIELD]['#group'] = 'domain';

    // Add the options hidden from the user silently to the form.
    $manager = \Drupal::service('domain.element_manager');
    $form = $manager->setFormOptions($form, $form_state, DOMAIN_ACCESS_FIELD);
  }
  else {
    $form[DOMAIN_ACCESS_FIELD]['#access'] = FALSE;
    $form[DOMAIN_ACCESS_ALL_FIELD]['#access'] = FALSE;
  }
}

/**
 * Implements hook_block_alter().
 */
function domain_menu_access_block_alter(&$definitions) {
  foreach ($definitions as $id => $definition) {
    if (strpos($id, 'system_menu_block:') === 0) {
      $derivative_id = NULL;
      if (strpos($id, PluginBase::DERIVATIVE_SEPARATOR)) {
        list(, $derivative_id) = explode(PluginBase::DERIVATIVE_SEPARATOR, $id, 2);
      }
      if ($derivative_id) {
        /** @var \Drupal\system\MenuInterface $menu */
        $menu = Menu::load($derivative_id);
        if ($menu->getThirdPartySetting('domain_menu_access', 'access_enabled')) {
          $definition['id'] = 'domain_access_menu_block';
          $definition['class'] = DomainMenuAccessMenuBlock::class;
          $definition['provider'] = 'domain_menu_access';
        }
      }
    }
  }
}
